[project]
name = "zelda"
version = "0.1.0"
description = "A Zelda clone for Thumby"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "thumby (>=0.4.1,<0.5.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
